### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by techninja1008** [greyshirtguy/ProPresenter7-Proto#8]
Thank you very much for your work in reverse engineering the file formats and producing these protobuf definitions! I've already found it extremely useful for performing automated checks on my church's lyric database.

I would quite like to start distributing some of the software I create with this, however in order to do so I would need a clear license for the contents of this repository. Please could you consider adding either an MIT or Apache 2.0 license? Thanks!

**Comment by greyshirtguy** [comment]
Knock yourself out.  This was the reason for reverse engineering them!
https://github.com/greyshirtguy/ProPresenter7-Proto/blob/master/LICENSE

**Comment by techninja1008** [comment]
Thanks for considering this! Unfortunately I'm not comfortable using something that uses the unlicense due to its unclear legal meaning(1) - would you consider choosing a more conventional restriction-free license such as BSD0, ISC or MIT?

1. https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

**Comment by greyshirtguy** [comment]
I chose the unlicence on a whim - mainly because these protocol buffer messaage definitions are not hand-written by me -they are _kinda_ [reverse engineered](https://greyshirtguy.com/blog/propresenter-7-file-format-part-2/) via .net reflection and I would _guess_ that I have no legal ownership/copyright over these files...

I am not _extracting_ these files as they don't exist... but I am building them using reverse engineered info - which I guess makes it a rather grey situation in terms of legal ownership and copyright.  I don't think RV minds - but if someone ever built a successful competing product using these files than I imagine RV might take an interest in exercising the "no reverse engineering" clause of their license agreement.

I don't think it reall matters at this point... and I am happy to change it to MIT - but just wanted to make sure you are aware of the  "grey" nature of these files...
